### ISSUE TITLE
Custom build of built in web pages do not function correctly

### ISSUE THREAD

**Issue by micgresham** [cotestatnt/async-esp-fs-webserver#30]
I followed the instructions to create a custom version of the edit pages using the instructions:

```
If you want customize /setup webpage (headers, logo etc etc):

edit the source files as your needs (setup.htm, app.js, style.css)
open a terminal in build_setup folder and run npm i to install all nodejs modules needed
run node minify.js
overwrite the content of setup_htm.h inside /src folder with the new generated file
```
But none of the JS elements work afterwards.

Suggestions?

**Comment by cotestatnt** [comment]
The script only works on the /setup page because it works specifically on the files on that page.
If you want to use it with the /edit page you need to modify it appropriately.

My advice, however, is:
- use online tools to [minimize CSS](https://csscompressor.com/) and [Javascript](https://www.toptal.com/developers/javascript-minifier) (optional, it is only for reducing the size of file)
- create the gzip file of the minimized /edit page (for example using 7-Zip) 
- finally with this [little program](https://www.segger.com/free-utilities/bin2c/), create the C array to copy&paste into the library (the page is not updated, Bin2C is no longer a command line tool)

![image](https://github.com/cotestatnt/async-esp-fs-webserver/assets/27758688/58ee18a6-50fe-47b5-ac70-2a9ebe22c862)

**Comment by micgresham** [comment]
I spoke in error.  It is the/setup page I tried to customize.  The changes worked, but none of the buttons (js) worked when it moved the setup.h as instructed.

**Comment by cotestatnt** [comment]
Check the browser dev-tools console (press key F12).
You probably made some small mistake which interrupts the functioning of the js script.

When I want make changes to the `/setup` page, I copy the 3 files (`setup.htm, app.js, style.css`) into the microcontroller's flash memory and I modify directly using builtin `/edit` web page.

When everything works as I want, I minimize the sources and then create the `setup.min.htm` file.
If this also works without problems, I proceed to create the .h file to insert into the library.

**Comment by mano1979** [comment]
> Check the browser dev-tools console (press key F12). You probably made some small mistake which interrupts the functioning of the js script.
> 
> When I want make changes to the `/setup` page, I copy the 3 files (`setup.htm, app.js, style.css`) into the microcontroller's flash memory and I modify directly using builtin `/edit` web page.
> 
> When everything works as I want, I minimize the sources and then create the `setup.min.htm` file. If this also works without problems, I proceed to create the .h file to insert into the library.

The problem with this however is that the "custom html" is not shown.

In my case, the custom html tab doesn't show up at all. i tried to do it with minify.js and manually with bin2c.exe, but in both cases, the custom html does not show.
