### ISSUE TITLE
access control

### ISSUE THREAD

**Issue by rob040** [cotestatnt/async-esp-fs-webserver#7]
This is a very powerful library for changing settings and files and performing updates.
However, with its power, it is also just too easy for others to corrupt your iot device.

Have you any plans of introducing simple password protection?
Or is it possible to add password protection in the existing API?

**Comment by cotestatnt** [comment]
Hi @rob040.

Yes, it is one of the things in to-do list.
Since this kind of authentication is already supported from ESPAsyncWebserver itself, it's quite easy add an option to allow authorized only for /setup webpage.

I would like to do something like FS web editor
`server.setAuth(user, password);`
for example.
