### ISSUE TITLE
Is is possible to edit and re-compile the setup and edit web pages?

### ISSUE THREAD

**Issue by micgresham** [cotestatnt/async-esp-fs-webserver#8]
I would like to change various elements on the /setup and /edit pages (color, layout, etc).  I am not sure how to proceed give that these are converted to binary on setup.h and edit.h.

Again, I would like to edit or replace them as I am tight on code space.

-michael

**Comment by cotestatnt** [comment]
Hi @micgresham 

Yes it is. 
This issue is similar to https://github.com/cotestatnt/async-esp-fs-webserver/issues/9

For the `/setup` web page the sources are more readable because i've wrote from scratch.
The `/edit` instead is taken from one of the ESP8266 core examples (FSBrowser.ino). The Javascript side it's a little bit more difficult to manage because it was un-minified from that source.

I usually put these files directly into the ESP32 filesystem so I can make changes and directly evaluate the result.

When I'm satisfied, I overwrite the content of files on my PC and then run the script  as described in this [readme](https://github.com/cotestatnt/async-esp-fs-webserver/blob/master/built-in-webpages/setup/build_setup/readme.md).
